# Generated by Django 6.0.6 on 2026-06-30 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProyectoGondola",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=200, verbose_name="Nombre del Pasillo/Góndola"
                    ),
                ),
                (
                    "largo_gondola",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        verbose_name="Largo de góndola (m)",
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="CalculoCamara",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "base_mayor",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Base Mayor (m)"
                    ),
                ),
                (
                    "base_menor",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="Base Menor / Cobertura útil (m)",
                    ),
                ),
                (
                    "altura_gondola",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="Altura enfocada (m)",
                    ),
                ),
                (
                    "solape",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="Solape requerido (m)",
                    ),
                ),
                (
                    "distancia_cabecera",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.5,
                        max_digits=5,
                        verbose_name="Distancia a cabecera (m)",
                    ),
                ),
                (
                    "area_perdida",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "distancia_entre_camaras",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("cantidad_camaras", models.IntegerField(blank=True, null=True)),
                (
                    "gondola",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calculo",
                        to="calculadora.proyectogondola",
                    ),
                ),
            ],
        ),
    ]
